export default {
  profile_pic: {
    marginTop: "20%",
    marginLeft: "auto",
    marginRight: "auto",
  },
  profile_picw: {
    fontSize: "100px",
    marginTop: "50%",
    marginLeft: "10%",
    color: "#ffffff",
  },
  profile_picz: {
    marginBottom: "-5%",
    marginTop: "5%",
    marginRight: "-20%",
  },
  close: {
    backgroundColor: "#e9ebf0",
    borderRadius: "8px",
    paddingTop: "2%",
    paddingBottom: "2%",
    width: "93%",
    marginLeft: "4%",
  },
  open: {
    backgroundColor: "#e9ebf0",
    borderRadius: "8px",
    paddingBottom: "4%",
    width: "93%",
    marginLeft: "4%",
  },
  button: {
    height: "100%",
    width: "100%",
  },
  camera_pic: {
    fontSize: "20px",
    marginTop: "18%",
    marginLeft: "50%",
  },
  top_text: {
    fontSize: "20px",
    marginTop: "43%",
    width: "100%",
    color: "#ffffff",
    position: "absolute",
  },
  top_subtext: {
    fontSize: "15px",
    marginTop: "50%",
    width: "100%",
    color: "#BABABA",
    position: "absolute",
  },
  top_menu: {
    fontSize: "200%",
    marginTop: "20px",
    position: "absolute",
  },
  info: {
    fontSize: "130%",
    width: "100%",
    color: "#000000",
    fontWeight: "bold",
    marginLeft: "5%",
  },
  info_container: {
    marginTop: "10%",
    marginLeft: "5%",
  },
  info_container2: {
    marginTop: "10%",
    marginLeft: "5%",
    marginBottom: "2%",
  },
  box_container: {
    marginTop: "5%",
    marginLeft: "5%",
  },
  info_title: {
    fontSize: "95%",
    width: "100%",
    color: "#000000",
    fontWeight: "bold",
  },
  info_content: {
    fontSize: "90%",
    width: "100%",
    color: "#353535",
    marginLeft: "5%",
  },
  info_content2: {
    fontSize: "90%",
    width: "100%",
    color: "#353535",
  },
  header_end: {
    backgroundColor: "#ffffff",
    marginTop: "-50px",
    width: "100%",
    height: "22%",
    borderTopRightRadius: "100%",
    borderTopLeftRadius: "100%",
  },
  grid_container: {
    width: "100%",
    height: "100%",
    backgroundColor: "#ffffff",
  },
  map_container: {
    marginTop: "10%",
    marginLeft: "10%",
    paddingBottom: "30%",
  },
  share_button: {
    position: "fixed",
    width: "15%",
    height: "7%",
    marginLeft: "5%",
    marginTop: "96%",
    zIndex: 999,
  },
  add_button: {
    width: "15%",
    height: "50px",
  },
  progress_bar: {
    height: "1.5%",
    width: "90%",
    marginLeft: "5%",
    marginBottom: "5%",
  },
};
